apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metrics-server-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://kubernetes-sigs.github.io/metrics-server/
