apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server-release
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metrics-server
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metrics-server-repo
      version: v3.13.0
  interval: 1m
  install:
    createNamespace: true
  targetNamespace: metrics-server
  values:
    apiService:
      insecureSkipTLSVerify: false
    tls:
      type: cert-manager
    args:
      - --kubelet-insecure-tls
