apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trilium
  namespace: flux-system
spec:
  chart:
    spec:
      chart: trilium
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: triliumnext
      version: 1.3.0
  interval: 30m
  timeout: 5m
  targetNamespace: trilium
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    controllers:
      main:
        containers:
          trilium:
            image:
              repository: triliumnext/notes
              tag: v0.95.0
              pullPolicy: IfNotPresent
    configini:
      general:
        instanceName: ""
        noAuthentication: true
        noBackup: false
      network:
        host: "0.0.0.0"
        port: 8080
        https: false
        certPath: ""
        keyPath: ""
        trustedReverseProxy: true
    ingress:
      main:
        enabled: true
        hosts:
          - host: trilium.kennyandries.com
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: trilium-pvc
