---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: servarr-release
  namespace: flux-system
spec:
  chart:
    spec:
      chart: servarr
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: servarr-repo
      version: v1.2.2
  interval: 1m0s
  install:
    createNamespace: true
  targetNamespace: servarr
  values:
    jellyfin:
      enabled: true
      ingress:
        enabled: true
        hosts: ["jellyfin.kennyandries.com"]
        annotations:
          external-dns.alpha.kubernetes.io/target: traefik.kennyandries.com
      persistence:
        config:
          enabled: true
          # existingClaim: servarr-jellyfin-config
          size: 4Gi
        media:
          enabled: true
          existingClaim: servarr-jellyfin-media

      resources:
        limits:
          memory: 8Gi
          cpu: "4"
        requests:
          memory: 256Mi
          cpu: "0.2"

      image:
        repository: lscr.io/linuxserver/jellyfin
        tag: 10.11.5

    sonarr:
      enabled: true
      ingress:
        enabled: true
        hosts:
          - host: sonarr.kennyandries.com
            paths:
              - path: /
                pathType: ImplementationSpecific
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: traefik-system-oidc@kubernetescrd
          external-dns.alpha.kubernetes.io/target: traefik.kennyandries.com

      persistence:
        enabled: true
        # existingClaim: servarr-sonarr

      resources:
        limits:
          memory: 2Gi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"

      image:
        repository: lscr.io/linuxserver/sonarr
        tag: 4.0.16

    qbittorrent:
      enabled: true
      ingress:
        enabled: true
        hosts:
          - host: qbittorrent.kennyandries.com
            paths:
              - path: /
                pathType: ImplementationSpecific
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: traefik-system-oidc@kubernetescrd
          external-dns.alpha.kubernetes.io/target: traefik.kennyandries.com

      persistence:
        enabled: true
        # existingClaim: servarr-qbittorrent

      resources:
        limits:
          memory: 2Gi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"

      image:
        repository: lscr.io/linuxserver/qbittorrent
        tag: 20.04.1

    prowlarr:
      enabled: true
      ingress:
        enabled: true
        hosts:
          - host: prowlarr.kennyandries.com
            paths:
              - path: /
                pathType: ImplementationSpecific
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: traefik-system-oidc@kubernetescrd
          external-dns.alpha.kubernetes.io/target: traefik.kennyandries.com

      persistence:
        enabled: true
        # existingClaim: servarr-prowlarr

      resources:
        limits:
          memory: 2Gi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"

      image:
        repository: lscr.io/linuxserver/prowlarr
        tag: 2.3.0

    flaresolverr:
      enabled: true

      image:
        repository: ghcr.io/flaresolverr/flaresolverr
        tag: v3.4.6

    jellyseerr:
      enabled: true
      ingress:
        enabled: true
        hosts:
          - host: jellyseerr.kennyandries.com
            paths:
              - path: /
                pathType: ImplementationSpecific
        annotations:
          external-dns.alpha.kubernetes.io/target: traefik.kennyandries.com

      persistence:
        enabled: true
        # existingClaim: servarr-jellyseerr

      resources:
        limits:
          memory: 2Gi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"

      image:
        repository: docker.io/fallenbagel/jellyseerr
        tag: 2.7.3

    bazarr:
      enabled: true
      ingress:
        enabled: true
        hosts:
          - host: bazarr.kennyandries.com
            paths:
              - path: /
                pathType: ImplementationSpecific
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: traefik-system-oidc@kubernetescrd
          external-dns.alpha.kubernetes.io/target: traefik.kennyandries.com

      persistence:
        enabled: true
        # existingClaim: servarr-bazarr

      resources:
        limits:
          memory: 2Gi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"

      image:
        repository: lscr.io/linuxserver/bazarr
        tag: 1.5.4

    radarr:
      enabled: true
      ingress:
        enabled: true
        hosts:
          - host: radarr.kennyandries.com
            paths:
              - path: /
                pathType: ImplementationSpecific
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: traefik-system-oidc@kubernetescrd
          external-dns.alpha.kubernetes.io/target: traefik.kennyandries.com

      persistence:
        enabled: true
        # existingClaim: servarr-radarr

      resources:
        limits:
          memory: 2Gi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"

      image:
        repository: lscr.io/linuxserver/radarr
        tag: 6.0.4

    lidarr:
      enabled: true
      ingress:
        enabled: true
        hosts:
          - host: lidarr.kennyandries.com
            paths:
              - path: /
                pathType: ImplementationSpecific
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: traefik-system-oidc@kubernetescrd
          external-dns.alpha.kubernetes.io/target: traefik.kennyandries.com

      persistence:
        enabled: true
        # existingClaim: servarr-lidarr

      resources:
        limits:
          memory: 2Gi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"

      image:
        repository: lscr.io/linuxserver/lidarr
        tag: 3.1.0

    cleanuparr:
      enabled: false
      ingress:
        enabled: true
        hosts:
          - host: cleanuparr.kennyandries.com
            paths:
              - path: /
                pathType: ImplementationSpecific
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: traefik-system-oidc@kubernetescrd
          external-dns.alpha.kubernetes.io/target: traefik.kennyandries.com

      persistence:
        enabled: true
        # existingClaim: servarr-cleanuparr

      resources:
        limits:
          memory: 2Gi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"

      image:
        repository: ghcr.io/cleanuparr/cleanuparr
        tag: v2.4.7
