apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: servarr
  labels:
    app.kubernetes.io/name: jellyfin
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyfin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jellyfin
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: jellyfin
          image: ghcr.io/hotio/jellyfin:release-88e2b7c
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - name: http
              containerPort: 8096
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 5
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /data/media
          resources:
            limits:
              memory: 8Gi
              cpu: "4"
            requests:
              memory: 512Mi
              cpu: "0.5"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: servarr-servarr-jellyfin-config
        - name: media
          persistentVolumeClaim:
            claimName: servarr-jellyfin-media
