---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager-repo
  namespace: flux-system
spec:
  interval: 1m0s
  type: oci
  url: oci://quay.io/jetstack/charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager-webhook-hetzner-repo
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://vadimkim.github.io/cert-manager-webhook-hetzner
