---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-release
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
      version: v1.19.1
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: cert-manager
  storageNamespace: cert-manager
  targetNamespace: cert-manager
  values:
    crds:
      enabled: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-webhook-hetzner-release
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager-webhook-hetzner
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cert-manager-webhook-hetzner
        namespace: flux-system
      version: v1.4.0
  interval: 1m0s
  releaseName: cert-manager-webhook-hetzner
  storageNamespace: cert-manager
  targetNamespace: cert-manager
