apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: cert-manager/cert-manager
      version: v1.19.1
      sourceRef:
        kind: OCIRepository
        name: cert-manager
        namespace: cert-manager
      interval: 10m
  set:
    - name: installCRDs
      value: true
