---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hetzner-secret
  namespace: cert-manager
spec:
  encryptedData:
    hetzner-secret: AgCU0qWGN38XrfM8eY9ZxXLgZEuC/0AdRllBAPVxDNVI049QS6cEtqhCjAV5QNhH0soQKcN6ti+A0d+gnyiYCLpgfI8/mWUN4lIncimxKW/uI9pQZcTxJOQCBK6unhYKq21E9BhkRhGLaEwoREfF+Pm8CzHKYGT0B6EAEqgq1oA3qpcwrIv7zrRzGb1KfOItaSWkB17WRj9pW6scKewagRx+9flFaIV0bAmnlfdQezOmg6TUXryBW6qLfY1ODtlbp/SKaEbELLGzmkX3Vss5tYgbkJ+jLOlU2daOhwKJlUCGozuCIFT3Y0ewGMH2+oBQQIbQRQpiO/0vI9N+E1/xd+rfz23LTK6ymVsWCjaoOohDgT/+TY0/IMmD528Les8cD3GH12y1ibblOF3td/Vu8o3joMeAkz6D3yzHpw3mZJFkVue71+IuMuVyXVi8mVdGaJYQ7N/P5Dv2S2FPdzSpo3YLGWRJVNY7S54hWYp1YDniHnSwNvA8oy4jLYFzM3x+pdtGnR3mNfy3JmEVsYGjjfBxtzcPKcXNNwIVZeEnHH8B7v2WKOSC7bO5prra5dm2iQ1MEbG2PfoSdKbtJKmsZnMdboyPx01BuWm4mCePcETnrk5Q43cYL3bK02ZxCT4ZlnF3VWxq7OA6AtEJaw7+Z0GldP55FoUiyiQQxa71LCCUtsSJksUt0wSkJouEq4rxQoqWhC6pZIVvtxwEW0NmWj4Dr2QL+q2/l1U=
  template:
    metadata:
      name: hetzner-secret
      namespace: cert-manager
    type: opaque
