apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hetzner-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgA6i4LGOaFaY8zCiPlXqtz+0t2qkAooFpBIqhMZ/o5a3WcFd3YIdTczQM8KSeqaXLz5wZgdGRn+v6gJunWozBn+4T/krQCtLJv0HUOaa+CqdaFjXY0w6VhWsB3uuMR+t9kjCFxST9ySVmA1KGIDN+YAzicIVhS4NzzPvTv4g2c+f9qZGER9Bsd8MkBCi0g0hrlJSerOois9CL32g4nQDQcrTnFMKC5qarJpFrKk6K1qRBlNCYfnvg+r/LeHSIhBkn7HBN9iwofPqQZCajziepc1KXKIiUuLffmfVN/4A/sMGDESvb3aas97WPPk2yeZtGDAebvPPqtmXFlJA/LLnNVRBBI+kbYPrfv2qxB3AT7Txxsq4Ti4Dy0WPdL1Zq6UmKJM8Thd2t3PKqXA1S0BJSpIBNm0lPSsZWu/6gTiic4CwifAf+LrKvqskso+8+bq1uKjZswznrgi4UMtqtMx/bC//djBuzjIbRX4Qaz5HQobHWuMoB2Ux7fxK+D+WmZA3XNbcftsnN9eVP8lRswFZWfHkih0RqLhp3Ya5k//xIBTxHX/H4ZQOeTdkHhqfD5l5xdWhpnIoqt5SbqxhV5HT5/4clG/qmRVY8yBGpB0T4YH6238+1LTsyv3ZjjDukpzwXr+RwPQKEYMG+MmyaR86rwK88LvnI46MsVAwYiMDJwiF4kXVYO67k6PW0Mo4l1YlrCTkPCS9NHtFWBAL39feGvULeRVI4x4W6u3UL1B/EpD5w==
  template:
    metadata:
      name: hetzner-secret
      namespace: cert-manager
    type: Opaque
