apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actualbudget-release
  namespace: flux-system
spec:
  chart:
    spec:
      chart: actualbudget
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: actualbudget-repo
      version: 1.8.6
  interval: 30m
  timeout: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  targetNamespace: actualbudget
  values:
    ingress:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/target: traefik.kennyandries.com
      hosts:
        - host: actualbudget.kennyandries.com
          paths:
            - path: /
              pathType: ImplementationSpecific

    persistence:
      enabled: true
      # existingClaim: actualbudget-volume
