apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: flux-system
spec:
  values:
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: traefik-system-oidc@kubernetescrd
        external-dns.alpha.kubernetes.io/target: traefik.kennyandries.com
      hosts:
        - host: uptime-kuma.kennyandries.com
          paths:
            - path: /
              pathType: ImplementationSpecific
    volume:
      enabled: true
      existingClaim: uptime-kuma-uptime-kuma-pvc
    image:
      repository: louislam/uptime-kuma
      tag: 2.0.2
