apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: flux-system
spec:
  chart:
    spec:
      chart: uptime-kuma
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: uptime-kuma
      version: 2.24.0
  interval: 30m
  timeout: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  targetNamespace: uptime-kuma
  values:
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: traefik-system-oidc@kubernetescrd
        external-dns.alpha.kubernetes.io/target: traefik.kennyandries.com
      hosts:
        - host: uptime-kuma.kennyandries.com
          paths:
            - path: /
              pathType: ImplementationSpecific

    volume:
      enabled: true
      # existingClaim: uptime-kuma-volume

    image:
      repository: louislam/uptime-kuma
      tag: 2.0.2
