apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trilium
  namespace: trilium
  labels:
    app.kubernetes.io/name: trilium
spec:
  ingressClassName: ${ingress_class}
  rules:
    - host: trilium.${domain}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trilium
                port:
                  name: http
