---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: trilium-oidc-secret
  namespace: trilium
spec:
  encryptedData:
    clientId: AgAI4YdBuB3Ze8X09bMnW55DuiiScZ/RidSCGCu+saozgzKUn7IXo0mxr70gYYDIfp4ebCPODFDXG2zrLsNZP7O5Vvy8qXSRuvd2jLksB5aYVfdUqKfZWAbqasjZP9FTw66NoMXDgXnJZTJs/1ljnya8EtDqkGbpyMOIC/D0ywZruVkwCOIZTCo8fFo8ETplZ+1KrUVDpyK/op2aqXRGGWpnh3aCxS4jD64xJ2rzjeqERE2UWV++6c7NkZBvHtt76xAfwdcEYa+q+uqT2xyEiKVvZxVw5SFsNX4D2pLi+oyqWtIhosX4tNYiBfD9ilCdZ162uTrp2+rW7y0HlqC5cQiuLq4yU9vaJVS3y1s+rWdyLt4cKdr2NhLZpajIS4xrgXaJBIUp2gHWj+lulb02tkJD/GGgs6qcp9p7YsTQFlXfRI7KFNwq5vBZCy1pV99gwxgosTKBCrsK/eMBU/9cSfIWGSvWPqKgiOLaX7P2lVXbYJ6pu37XRoCipPQbfw3Nce73bm9xydudSLLCdgcrBetlLBLYGCkgXRtkPptdqwWDBJ/rZohHeBt5mCbNhjrjFzDLG5MRsX02i2QheU7m38HKHyxXUctyMTnCbzVcUPyfTazFkqU+E+x41+C8kejvMxwpfWoKSKiw6TyRXTb/whsoKjv2DjjcgBXTkva/cXLBzFWHIpIX6iIofJlijV3cUbzW7nSky94Sh749HQUEaMCF7C+rh7dfXV0J+DKvXStfoGMl3LA=
    clientSecret: AgBuEGukBZqOHnb/7N+PcMuc+yIWS2paizOaRP9+EQyt/7Jc9kmzax6zutN605QkDfDr/8nfXNG9cI6Fqnu/3kJu8JAGCOgqDPb8Ne5yTsxqf4dnoaZW0aDAuwdAQQ+hh+IJ9XDeBkWna+RuMGRnzPqDC6kKW39B0b692ctRWOXKpWiYfckRfxXeYRcrLzYPGF/U6uadsvahG/PrnHkAG5VoTe4dba5Z1uVFllEntswURW9oYbx/7IA3vgCgcUKCANlOpRyUBboMvwuMwlT6Qj64mpf4C3iv0cxrxIZ05Jxrio4n/pBF/Q3l7916ANd8oyc4bM62Upf/dzPm+Q3rlhiIMO0yiEURI4Ctqr6PFJlk9kfhJyl0t2U+6Xz2vCXWiwjo/IZe9M2TlOoXeHzCBGagFReHdhLebXMETqhChVcabCAO2lMyh9Sq15x5XJgfKoceoRoo+w+/vbg3SIgn1DeUP7IX75FVaTR1dwpgqvTLl9Aj2oWywDoGtM16/S9m4QJxX1GfaLfsd9Fuh+hZG+w9H9hOuqZTrnYYEGgswU1/xDv6c2qvrLY8YsNgsQ2lZZAN/GgeVkC6c3u6thyYdLSFjVEqaEuRMyvQlX/nT3g0Gm8+gNBRo9oPYCpWiobnH3wE+FQGWbsXcamR9QSH1M44s0LD61EAWomKtMZJ4dcIwerMyyLaMjU4Odg9JuVjIP//EjrkZIDHnw90OXWMqMNhhjQy1Kmm1XkJyOBY0XsZMg==
  template:
    metadata:
      name: trilium-oidc-secret
      namespace: trilium
    type: Opaque
