apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: servarr-servarr-radarr
  namespace: servarr
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    app.kubernetes.io/name: radarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
