---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-gpt-secrets
  namespace: paperless
spec:
  encryptedData:
    PAPERLESS_API_TOKEN: AgB8dh4S1HFbqljFubfTzygfG8a7w+sC9p+8CIgD0B/uQQurujKJLzBuAHyHrUCJW9HK20GYKTjc7SBdFj0Z/Gkt6G++0aG3tYOvoYAjpeTYS5QX2BABJ7+DTLmIOdMMo0p2BRjaacGI1U8sBK8iCgSTHJD5kb3XF8ytK7vp7BwTXZY5tRnKukadtmuwFIXtqbuxyVRAu5HjmK4NOF0DoSxX4h+Z/PnX/Vv/RlHtmzDjlYXZE3vG0nT/775NQTcxS9WaW3y281FJBe+ImyH6G++JdqU0+eOt2iCs5GjeGyjQLknIgHya73FHyg9v41rXtCX5xLKQRJJCcv+sEaLz5vcwNJp/AAS6O38warHARsQRpXdDnrBMc8VXeni5AUpfXdwkkV7StXgoezbUxDoDOswpyvO2+F4+i5aMJfqNqh8ScTA05bmqjCaejDhUo0AhstMmQ0d471foYIVKVpuOOdg5yOZIGgsbCv1UoFz5ur80+2fQ3viYI8xWB1X8nc5us77H7J1wpTolTd+WK+duwz30FPY9+fErSABt10J1OTimOBfmeWJPmJKxuri1wtQqIiFOIxSkLuakXRDFSodS5Q+1jpuFUAdmjgxlSORSxkCdiC3mv1xjB+VkpalYulNqdhJpKMi6gEloDf8TVEE2F+XJYiUJ+Q0Q8Uk4q/7QjJ87YmijLlsOppYr5t71wAcuUxqKSbjmSql9q13Mmv1VNx51JqhhfDJke+NPHnNYpBMNvIDpir/vZ62u
  template:
    metadata:
      name: paperless-gpt-secrets
      namespace: paperless
    type: Opaque
