---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-gpt-secrets
  namespace: paperless
spec:
  encryptedData:
    ANTHROPIC_API_KEY: AgBL1FsUGLFQpWP1zJAIvBHySrSkPow2rNbuIM1llTXF4FsJOzRyiZ5BK9tvBEXf/rZKzNCcMfP9u+02BwnLsxYgFSzBS7S6qIhSHPzhHULKcHPMsJPv0Ujj+jJ5PJBUKB+0a9bH1pr7PQxmPEDSE7rURTqZgo2qiHy+T8fRdBcWyz9HnqeElg35TY6Cig3ShFZ8mPNpSzoBuHWW+7M68BZNzFekSwiGlMNhPmgbkzTAuh1AL+j46wmAQobZ9jVR46N6cRCOECpwOirW7VICQT+ZamBI10ybxVDIJuVGOV8rrDuRRfKmcO28lbgngiuR6RTSo1BttNc3G0PqghzpKV4rN9YNZAfJ3mSLWTT7i62AfvTbs/veLsHvvB9nICaN+FWrvqft4wnkWvX9GvVwyu/Uq33s1oW1P2XU+6K0zStvQVCEIfrZ2+FPtySbz2TzWDQM7eXBh/WC3qV5hJg2IUg7U5uF6W29xf+MUDMpGmr6pAL7tosIjLFgWjtflfMf+5F/EXqRf+oKvE92sxUNLJYqoNKvTdVloV8y9hbzWNAX3EFOlAzTbNnB1WF7vxVtgLYvyqjSjUND5/ysSawFXIXVO5GC13rTjWHX79nuaa59v7u0ONkHC/2Zfw8/aA0znzenucPIQebI1kxEd+k7p6WsSPE1DHYjLszyQWv/Gdx5if00VNtwGn4FUri60j8xz/xiN7GI0GPTZ7a9/TClG4xfK+CF01LurMUw8pRRzaWrUWVblTe8vrBWu3vAirMet+2uFbM7BGd3AUgjCuuN3vbkLtQ87lkCqe9xkUFa2QWYSCP5QSnrzmEb5CX+8nIzM2xL8JmGOEweGzUoEww=
    PAPERLESS_API_TOKEN: AgBNq3NNQeR9z+y88G4C1L+NDJ7MKUezPElmfuMqAbyk+7kUyOG5Su0iebeLKQHWOiV6TBRVW+4KDSA/dxnhoz1xG5fNh62VwHUgCjMr21ZSECCbWvxOq+xDoAd9n0kbKB5HO6veYf+W/RxTx74B22S9EyHgid43B1xKzGfPOdOYwdNKbo3MY/5z5LVhsbSTLN2DVb4XOTVVRDabXCbZJFtxI1h4PVehlR6pv8qFUgyCILhlDjBDzMfHJNe3uxH7XZB3ujOxcK80NK4VcOhFwKTJAA+tITknrsjwY0ejdGTSzacxwnWqlDAoLPYKF88K7sjTo71dduI6S6OpeixsywTHkTehjm8N/OmWEFpbfPowYACLOq4MCtrPDONpO1bi+Ck8jUnPo4uNRKVcVhiYzURrXk04g94tGfe6Hvnbj/HZTb1xADPK9cwu1lLiO5FPbRRSZVy6BhM3fPklBpNv6lng6+PQxNHpDOTQgCN8D8m4HwGhXwnCLfKxpJd/mxlKOTMYJ9ggYHGyYAZcHyADyoVJw8+yrICpqH1oA6V/zahhqeGGzicFlVSBNPvH2pkXopIJX43sQu7YP0+AnIPk4wRlWawi6L716F/qAaGH3J55Vu2kvqstfDVOkUhg13hjU9kWVtiaE62Y0MWb3sZQkx8loJolhWRyelMrkElV1RMPGDJ9A3Dj6QXkVou8xHrCudZm2jhLwYxsDwUgVpL6iy+jO5yZSZAbHrAtOsKlPXPqZwz5rn4HLwb/
  template:
    metadata:
      name: paperless-gpt-secrets
      namespace: paperless
    type: Opaque
