apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lidarr
  namespace: servarr
  labels:
    app.kubernetes.io/name: lidarr
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: traefik-system-oidc@kubernetescrd
    external-dns.alpha.kubernetes.io/target: traefik.kennyandries.com
spec:
  ingressClassName: traefik-system-traefik
  rules:
    - host: lidarr.kennyandries.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lidarr
                port:
                  number: 8686
