apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-data
  namespace: code-server
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    app.kubernetes.io/name: code-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
