apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: servarr-sabnzbd
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
