apiVersion: v1
kind: Namespace
metadata:
  name: metrics-server
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    app.kubernetes.io/name: metrics-server
    pod-security.kubernetes.io/warn: restricted
