apiVersion: v1
kind: Namespace
metadata:
  name: reloader
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    app.kubernetes.io/name: reloader
    pod-security.kubernetes.io/warn: restricted
