apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: flux-system
data:
  cluster_name: production
  domain: kennyandries.com
  # Traefik IngressClass name (helm release "traefik" in namespace "traefik-system")
  ingress_class: traefik-system-traefik
  storage_class: longhorn
  external_dns_target: traefik.kennyandries.com
