---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-secrets
  namespace: immich
spec:
  encryptedData:
    DB_PASSWORD: AgB7xwlzpjCxqP78l2eQTq6aMFzWZd00SxV2nzQmiiaZ62oFi4XKknL836SE6aLpnSDnd2jdcSPRW/USp7DUsxf2NCHa2pNHU1Uvu5SeOit1ApscCc4YyxsxYX7+f63jd/wunkXPzLHKvYPkHOwiHk33sXotZpuxkqJ1fBbTQs5zdpAj2FuJ3fcUem4qA22HMWBu8gNItZLyL92Vu4KrQRp79i6IzbjVjF+wXhIA7YSK7bYDNahcIUltsShhMywdlLFrbh/ysuy7jdDaWv7M/Pfd7gxf7GejRUeqqMtMYHBwXJjZT0GlSW5T0QEIQLFpJyCaFvzEOrRY5dPthKVe1aSQwXc453QsFmDYNB1+JjlEs2iyV43CvVbW8yvEBisk4HDj6ryOLwdHuZY6J4vTailodx4PfSlZnsYBVuop8QPPIErGZ17VxFu67uMVfrvqGz426zXCd280NFREEDXBP7xEn7vpqTwz9CH31b0HYEMzXXhXrYZuys/VjiGt6dYGHXSPg6aIVKZs15CK9nF/tohEE/HcSnuEVRuXwZCkecXoHFNHvpcn5o3QQkf9zmrRJwGeXwmpSVFCW4Mutk8awz7cmt298QLzqYNPBGpv6T8CQQJtvNF+3WDHhk4njINcKXk70poo/W/GoiBimKSTz47yw/2cSl+99BiNEjyvdUxptC7B5wU8hqiKv31mS5ADrT8MjVhkESH9vB8rXtMhObM9d5wlMeh++ZK38es/chBC
  template:
    metadata:
      name: immich-secrets
      namespace: immich
