apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  chart:
    spec:
      chart: traefik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: 38.0.2
  interval: 30m
  timeout: 10m
  targetNamespace: traefik-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    replicas: 2
    ingressClass:
      isDefaultClass: true
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 65532
      runAsGroup: 65532
    securityContext:
      readOnlyRootFilesystem: true
      capabilities:
        drop: [ALL]
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        http3:
          enabled: true
        middlewares:
          - traefik-system-crowdsec@kubernetescrd
          - traefik-system-security-headers@kubernetescrd
          - traefik-system-rate-limit@kubernetescrd
    logs:
      access:
        enabled: true
        filters:
          statuscodes: "400-599"
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.kennyandries.com`)
        entryPoints:
          - websecure
        middlewares:
          - name: oidc
          - name: lan-only
    service:
      externalIPs: ["192.168.1.3"]
      spec:
        externalTrafficPolicy: Local
      annotations:
        external-dns.alpha.kubernetes.io/hostname: traefik.kennyandries.com
    tlsOptions:
      default:
        minVersion: VersionTLS12
        cipherSuites:
          - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
          - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
          - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
          - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    tlsStore:
      default:
        defaultCertificate:
          secretName: traefik-cert
    experimental:
      plugins:
        traefik-oidc-auth:
          moduleName: "github.com/sevensolutions/traefik-oidc-auth"
          version: "v0.16.0"
        crowdsec-bouncer-traefik-plugin:
          moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
          version: "v1.3.5"
