apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  chart:
    spec:
      chart: traefik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: 38.0.2
  interval: 30m
  timeout: 10m
  targetNamespace: traefik-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    deployment:
      kind: DaemonSet
    ingressClass:
      isDefaultClass: true
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 65532
      runAsGroup: 65532
    securityContext:
      readOnlyRootFilesystem: true
      capabilities:
        drop: [ALL]
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        http3:
          enabled: true
        forwardedHeaders:
          insecure: false
          trustedIPs:
            - 192.168.1.0/24
        middlewares:
          - traefik-system-crowdsec@kubernetescrd
          - traefik-system-security-headers@kubernetescrd
          - traefik-system-rate-limit@kubernetescrd
    logs:
      general:
        format: json
      access:
        enabled: true
        format: json
        fields:
          headers:
            defaultMode: drop
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.kennyandries.com`)
        entryPoints:
          - websecure
        middlewares:
          - name: oidc
          - name: lan-only
    service:
      externalIPs: ["192.168.1.3"]
      spec:
        externalTrafficPolicy: Local
      annotations:
        external-dns.alpha.kubernetes.io/hostname: traefik.kennyandries.com
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
    tlsOptions:
      default:
        minVersion: VersionTLS13
        sniStrict: false
    tlsStore:
      default:
        defaultCertificate:
          secretName: traefik-cert
    experimental:
      plugins:
        traefik-oidc-auth:
          moduleName: "github.com/sevensolutions/traefik-oidc-auth"
          version: "v0.16.0"
        crowdsec-bouncer-traefik-plugin:
          moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
          version: "v1.3.5"
