apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrelease.yaml
  - middleware.yaml
  - certificate.yaml
  - poddisruptionbudget.yaml
  - sealedsecret-crowdsec.yaml
