apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: traefik-system
  labels:
    app.kubernetes.io/name: traefik
spec:
  headers:
    stsSeconds: 31536000
    stsIncludeSubdomains: true
    stsPreload: true
    customFrameOptionsValue: "SAMEORIGIN"
    contentTypeNosniff: true
    referrerPolicy: strict-origin-when-cross-origin
    customResponseHeaders:
      X-Robots-Tag: noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
      X-XSS-Protection: "0"
      Permissions-Policy: "camera=(), microphone=(), geolocation=(), payment=()"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: rate-limit
  namespace: traefik-system
  labels:
    app.kubernetes.io/name: traefik
spec:
  rateLimit:
    average: 100
    burst: 200
    period: 1m
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oidc
  namespace: traefik-system
  labels:
    app.kubernetes.io/name: traefik
spec:
  plugin:
    traefik-oidc-auth:
      Secret: urn:k8s:secret:oidc-secret:pluginSecret
      Provider:
        Url: http://pocket-id.pocket-id.svc.cluster.local:1411
        ValidIssuer: https://auth.kennyandries.com
        Scopes: ["openid", "profile", "email"]
        ClientId: urn:k8s:secret:oidc-secret:providerClientId
        ClientSecret: urn:k8s:secret:oidc-secret:providerClientSecret
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: lan-only
  namespace: traefik-system
  labels:
    app.kubernetes.io/name: traefik
spec:
  ipAllowList:
    sourceRange:
      - 192.168.1.0/24
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: crowdsec
  namespace: traefik-system
  labels:
    app.kubernetes.io/name: traefik
spec:
  plugin:
    crowdsec-bouncer-traefik-plugin:
      crowdsecLapiScheme: http
      crowdsecLapiHost: crowdsec-crowdsec-service.crowdsec.svc.cluster.local:8080
      crowdsecLapiKey: urn:k8s:secret:crowdsec-bouncer-key:api-key
      crowdsecMode: stream
      updateIntervalSeconds: 15
