---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-bouncer-key
  namespace: traefik-system
spec:
  encryptedData:
    api-key: AgA/KMncKHPh00P7PJ7P3uRL7CMomthRrJ0dBya1Ul2yIVWeIhSboR0GBgEmz823pf7VLQ+vtg7KTUQDrYCo2Eap0FONzjkZ3KOSZYJKYwAVPNpEeEgpJrhtNfIt/I/UN3f/75jb360gTsSNfuuzY8OECC/LFUFJOzFQXW2LpqlDbwsLGOFcEzJuNYJLvQ9VnYsL3RqdMfhb9KsFN/IHAzJANaB1uDQdbWuNyoNFezMRhvmSOgyP9L1U9UwTc8WJ8Fo++LwcswGzXbnFCHLSEUmE+a5oeLqITiYQDjfacZ9yVja+rIMleOntPh2oI2/KqsCT/O3phy7Uu2moT1xtVWY9mqPbL+lijrAhxQTfmSfWEr8PgFFMDbP7JC4sRPsHgaFC6EX80wFuWSdDLqlxwReZ5ktnjRgQwywOzLwxpZ1Yavm/W7pN4FnhcJHbM5lu7EklrT5N86Zr7Gx30Pl2ZlGKBt8vl/brxVEqcKJawXk0Wd40QFJV80JZY+URRCfeYRsmXYvJP729GQtxH2aJCf/ReeGxJS3K/r3QdnUwNnEWo+HgwXG4xv8yRqMs2ZJnKD5UbhtEClCaKhHgGTlERbDq/ZggfvlmlNuysudkOedsQDZn9QIVE6SWZZCahB6d88Ege/TJ+XfVCAMKLRcdEWmGLiG3slCGtc90JIdSbnYtl5rRoNN4NSEHDw9K4hA5QlXNblB8fRmUPyWlEZyET56at5w5jnsNmzAyOuFM0p0NEWsWFOYJyIapgpGX3tbx
  template:
    metadata:
      name: crowdsec-bouncer-key
      namespace: traefik-system
