---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-bouncer-key
  namespace: traefik-system
spec:
  encryptedData:
    api-key: AgAITgi4dHM+/oZ7Ox+KhDUJT8Q+wyzuw8n5JeKsW1kqQwQsUEBBXLqJ+Gf0x2kkn7FmXbgNHr3CiFWvBalnA8DCGHk4Q8AETIT81P61j0F5dsEiKpZNznp83u92R+L7TI+gkoTHdqItjv2isTa/iPx3UkXQGBqSTc+3qiTnm5rtoHzkPldCtJP3wLJ8nUPVgsuUODP0gscGhho85oOq1gtZVNEVn/h++m0uxJT+IWdf5S3Ex9SHwezauLToA67pyEvSPZ69aFY6qEo2b0gC5lFtlECz5eQlGhBJ83JUxf6SCjVJVYzRc/fQjnss2QII2MVM3a+lo+UNnYSgPuwRNPvPwbTSbxVn1WR1dwGn729jjnqIbQZYDPU1aQ5w4S7WoI7EXUBFYOIBifbikcb+EpT8KV4PUwYaEiKdMT0hisFQiBNL4POv7hHfMnA5bVNGIX/0cQT0lgtU7/ht096vdq3aNGiTzVLYFO3skrZw8pbzePrLhJgizJK990npVPHONyxQ5XgPVApoJ20cw/6HlPWyvcXfKkR4Wk8tOLiuS8Nd13uWJZVQR8+6N/cCRv0MsdaS9smdavpj26cojEAkeer1QTKX6GxIXFVB2Cy7eFFhStUvbemDCoXT8Z6Kp8Pm6LIn2GOd45UqqTE9XSpdBD31dS5ok95onosRnoupxn+h+V/bgMZHmp3dF8+RwMJFaEB63zNbxMbwMSV9V1twZtkEbmEuOItgjUudx60wE/IIy0CEyE9V3LqQYayLag==
  template:
    metadata:
      name: crowdsec-bouncer-key
      namespace: traefik-system
