apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: servarr
  namespace: flux-system
spec:
  chart:
    spec:
      chart: servarr
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kubito
      version: 1.2.3
  interval: 30m
  timeout: 15m
  targetNamespace: servarr
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
