apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-app-data
  namespace: servarr
  labels:
    app.kubernetes.io/name: configarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
