---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pocket-id-secret
  namespace: pocket-id
spec:
  encryptedData:
    encryptionKey: AgBTW9sBkV2Qd5YVgURFkIn18HctHyPaPxE3wsXBEjyp/9rwG+KPfJXpD14wuG0+8h/jjyNLx89ihdljtFlbQFN2axVrMPbk9OvIeIWYVtfxO+De9HulXJSK/2HM4dZbcEfGIKMQ64bq7rQeunQp+tsa/yNyYqAg7UqqpokHXOVgl5N96jWS1KwgQSklSbJJ088qUtP/kOpJJfN+JYLJ3viLG4qZLqAX0kUQY+kRIIR90ZfyiMXKE4+5KoBb9BLFWPuhMtiddyPvxuOgf10ClyaFJRfJSHakbMjrMvwPtEDF3Amsvh7xb0lvesUY5r5B0043aI0e45UARvVBlrysEyc8lyzS8dJAZApZYMUhiXwej+fVZGQOzA45oPmzcQkayZufwQ//MCsUzkc3mgzpWgEcQ2F/TDVrmIGZ9WVM5d1iMzZvbPRPN3hJpKa6PBvp3CbWw+EsxtZEWUrcJIg+Xm8zAaeQY4KlkjwRIUWOxMeKhnplvMJvHJG/miaob9zoemMCCY0mR9WnRwoCtH2upE1mITBkGaKV6ZUsR3Xf1k0aVPyw49DdPrfekm1cgDOBy/xAQ+scRMD6b4ljhEAemK9XZUFn4XOspVuN+m7DDkQzHDKCNedpfQK0xiWbbO6twFs5scrZa3A03yAt1+6qbzt/JIC/jtH14tdI5+o4qVd4RptRbCONf3rNxrgy9uT70JaY16evDKfZTWC5yzbB48Vi+OhJM1VJrwDj0tUoQGjoWg==
  template:
    metadata:
      name: pocket-id-secret
      namespace: pocket-id
    type: Opaque
