apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: beszel-agent
  namespace: beszel
spec:
  template:
    spec:
      containers:
        - name: beszel-agent
          env:
            - name: LISTEN
              value: "45876"
            - name: KEY
              value: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFtkHpdRf++PWFRnVJFmH793bv8aSP8xbxY0ROhkEAxC
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: beszel-secret
                  key: apiKey
            - name: HUB_URL
              value: https://beszel.kennyandries.com
