apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: beszel-agent
  namespace: beszel
spec:
  template:
    spec:
      containers:
        - name: beszel-agent
          env:
            - name: LISTEN
              value: "45876"
            - name: KEY
              valueFrom:
                secretKeyRef:
                  name: beszel-secret
                  key: sshKey
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: beszel-secret
                  key: apiKey
            - name: HUB_URL
              value: https://beszel.kennyandries.com
