apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beszel
  namespace: beszel
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
