---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: flux-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
      version: 1.10.2
  interval: 1m
  install:
    createNamespace: true
  targetNamespace: longhorn-system
  values:
    ingress:
      enabled: true
      host: longhorn.kennyandries.com
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: traefik-system-oidc@kubernetescrd
        external-dns.alpha.kubernetes.io/target: traefik.kennyandries.com

    defaultBackupStore:
      backupTarget: nfs://192.168.1.21:/mnt/hpool/backups/longhorn
