apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: longhorn/longhorn
      version: v1.10.1
      sourceRef:
        kind: HelmChart
        name: longhorn
        namespace: longhorn-system
      interval: 10m
  values:
    ingress:
      enabled: true
      host: longhorn.kennyandries.com
      annotations:
        # traefik.ingress.kubernetes.io/router.middlewares: traefik-oidc@kubernetescrd
        external-dns.alpha.kubernetes.io/target: traefik.kennyandries.com

    defaultBackupStore:
      backupTarget: nfs://192.168.1.21:/mnt/hpool/backups/longhorn
