---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAdv8LE9Ksm0MJdtzWUMLWiD3Yy534z2SZ/RAzva0LPzZf4t+XH3E8MOYXVWwY5OplL8inar/ah9/PSWGOyoLsUy0iozcbSUXJIbGjp1P6sFVljL+zndov8or+GI9ezbDczqTHA0heswsRy4FjQIdBXgf3EMjDqjuVwQw9/9/5sHOOdWW0qjuFPJXYzkUVGN05/5ZtFmhhPF6WHrqcBhwh6Cg8p3ko2BRhAhUVVIMGe2xinw2BAxdNi/wPJweqqwJa3+WsnsSX9JyNviODlQxse3rxKP7+xUoLQQQBfua2ikxPBQB3MKFUMaUV7HEfFW1zYEYKCE+tlsdCoFXTgqatDDtjqShinrzJeRtyIWM8MWKBpZJRbd610anwffxXN29Oy7EiH30as3PEEpILb9HgiAHlEbpl2374A4UEE/8SUyh6M4yWXBRkBLHjlMmpylEL9ZrN2P2FcaiJym6UCvOcWbn+ntgdFtJBak8Qfy83OAKZUncr+FOGKLSTvhtWM8LICcvs6nHVXjoyBALIQTNl3HueXuqnTAPb3V+DcmtXkS2fMLeUgBTQuIQao82egbrRhD5EfoYBzX8UOB4FLQXm0eQnbNUDgxm9pnBSBrZXwKv5ooDzswvL/z1cLTJqesUuxscb5HlPE/xYu4QkymkWIaRQz/Ph8ZZtgc3YERz4xrcU1lo5YxlFjNBDzvi7x71e2FnW7j2XYnvMbGE+juMZje43yor8wgmTInGWYkQqInxL3a07OGfT4
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
