apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beszel
  namespace: beszel
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    app.kubernetes.io/name: beszel
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
