apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - sealedsecret.yaml
  - mosquitto.yaml
  - zigbee2mqtt.yaml
  - homeassistant.yaml
  - ingress.yaml
  - networkpolicy.yaml
