apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - sealedsecret.yaml
  - mosquitto.yaml
  - zigbee2mqtt.yaml
  - sealedsecret-speech-to-phrase.yaml
  - speech-to-phrase.yaml
  - piper.yaml
  - homeassistant.yaml
  - ingress.yaml
  - mqtt-ingressroute.yaml
  - networkpolicy.yaml
