---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: speech-to-phrase-hass
  namespace: home-assistant
spec:
  encryptedData:
    token: AgCE3nyZg2Y3Cehha5UjBIrugFttpaoEUTmQ91SluCVjP2B0CYZ+5gu9XuSdMKQoTsXSipXHLBdZ5j5ZnTvfZyetv6gEPBe6dwSJJbgciDyw78Yws5vqg7oYiqg/UC9l/eB5QFHZMGZgYKZgWI30r/n3wxAitbRsV/jjyl6yxaxP+mg+YRpRFvYwc4x/CCGDEvp0HcU4ILB7m1rQZ1+F2GzhT/zKL+g76BI3X54wTXbwkAAKGtndd8jv1z/JQVDXAwI1x6UnBKnOiUb0FGLf6L55hRU+kCktPxrACrkYSZicZz1j+t7DgQCcH0cJVT+tLD6eyl7F29DsCR3JUkKV/wryT4ISJ8mt8/9ZmX4pakg5euVfnZoy9yEBAoB/7t3yS6taBoUWMVgJH3JN2BQNe4JMvW3civobarRDwEYadnAqRRAHYws1K7g3hPI/xo4dpUNCcZMLcGbSqhHBCdgEXCXJONy+uMIGDQkGswNNHO3qGS8R1iC84LwJIiRpMlWg6yBVNmmTvgJzxc1oHPG008zQ9DzMrn2EAZdAGS74HLFdrKLPpJcB2aIIeDYDoMBEPlEvBEd+BCWjqM0irNUQOE2ZaIaOkXqCX0Lpm5xebkeAypAWM2l84V8Yk9o/qQ58XPAZgmBRUDftJmEh//flmhqFZ8RBGjVecs0WfJnhMMxiC3m9VDNXThzWcIiM12NaXZNzxrSmJpOEdUVfUhdYuNzZx61D5C2XmS64P7QLHqBHipkIztQgD9wdGw8F1gHMwEFZ7bSpNhQ1emhHdj1bNnk3gDSqKzaEY+pEbalJTEP3cCQ1Ii0iHLdkKi2YKmxdzbTAYoT7N1EOonE4wYrtBh1oYG0yF++WF8O6mAJ/GMN0Kz2puzRBhFQBzhie0jmtgAdwEZ11syMikxWifYKLF69YbUg5nz/7lvVoam/nzPPRjYkAex2j12E=
  template:
    metadata:
      name: speech-to-phrase-hass
      namespace: home-assistant
