apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - actualbudget
  - audiobookshelf
  - beszel
  - code-server
  - configarr
  - home-assistant
  - homepage
  - immich
  - jellyfin
  - seerr
  - lidarr
  - paperless
  - pocket-id
  - prowlarr
  - qbittorrent
  - radarr
  - sabnzbd
  - servarr-common
  - sonarr
  - trilium
  - uptime-kuma
  - vaultwarden
