apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - actualbudget
  - beszel
  - configarr
  - homepage
  - jellyfin
  - jellyseerr
  - lidarr
  - pocket-id
  - prowlarr
  - qbittorrent
  - radarr
  - sabnzbd
  - servarr-common
  - sonarr
  - trilium
  - uptime-kuma
