apiVersion: v1
kind: PersistentVolume
metadata:
  name: servarr-jellyfin-media-nfs
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    app.kubernetes.io/name: servarr
spec:
  capacity:
    storage: 2000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - rsize=1048576
    - wsize=1048576
    - hard
    - noatime
  nfs:
    server: 192.168.1.21
    path: /mnt/hpool/media
