apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actualbudget
  namespace: flux-system
spec:
  chart:
    spec:
      chart: actualbudget
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: actualbudget
      version: 1.8.6
  interval: 30m
  timeout: 5m
  targetNamespace: actualbudget
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: traefik-system-security-headers@kubernetescrd,traefik-system-rate-limit@kubernetescrd
        external-dns.alpha.kubernetes.io/target: traefik.kennyandries.com
      hosts:
        - host: actualbudget.kennyandries.com
          paths:
            - path: /
              pathType: ImplementationSpecific
    persistence:
      enabled: true
