apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actualbudget-data
  namespace: actualbudget
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    app.kubernetes.io/name: actualbudget
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
