apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrelease.yaml
  - networkpolicy.yaml
  - sealedsecret.yaml
  - deployment-unifi-bouncer.yaml
  - sealedsecret-unifi-bouncer.yaml
