apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crowdsec-enroll-key
  namespace: crowdsec
spec:
  encryptedData:
    enroll-key: AgA5IMUIxC0hHFbap33U1B2OLk5sZDyvq331fHQKXouIieru2E2/6Rk9CHGnn9GkBBA7uUP0/XuLsj5acf+MLPaWbsZdH0n0tnV3wzpdlD/1vv1d3u3aKK6Z4zH7kVKxrTiPYK2rOo5GB7PbIs3D8XblXSzf/dXrWbDGRuu4hkEFr7DCwnRA2bOcmPf+5oayjwyws/cdTDPkbM/31aHNEN7nGzUvEEDlmqtHV5bjdNP/A77D04QRy6fmLvhFdrf7SSyAQCLzHylZqIq4EQuAnsUH5AZq1GKh9Dpu4lDew6NzTk/T7BmcU7cDbraZuIOqy77oHq7ZiRCaszSGkcHpvqjfxd2YYeNEp/ywowlPqxeOloua8e7HMhviHaq5tRrvDTV9A2f3AIf6b4NAotPaIb954KspSmLFxNMNR7XrxCv8KJ+jL1qorCid5+MmDfBTYbjThYaeHshB8bj/vBjCozeX74cWxeSjERzssfI3NuUceGYv9b3Ogtce/P7iotOmqQYMRkYrrYHHJ5vhzjepZ6KWHR3xbJBzTWB5KXvB6XUErriw/BeWssswA7TaB+0J6/aNLi5WC9DuXU/F8E+oAozLDsIojnNHY9K1ytCjheYK3isCnj42MXOPJNfyFvSzUwy9vSLhtY64YxrHAEmLxxPlgUmjuFX178xIoWoMCBgNNBPMQhPQa3Ud4ymqzFH+tgI0jjckcKgFDghICrVTvNXEvV9pu4ISzD1z
  template:
    metadata:
      name: crowdsec-enroll-key
      namespace: crowdsec
