apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: coder
  chart:
    spec:
      chart: coder
      version: "2.34.0"
      sourceRef:
        kind: HelmRepository
        name: coder
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    coder:
      service:
        type: ClusterIP
      env:
        - name: CODER_ACCESS_URL
          value: https://coder.kennyandries.com
        - name: CODER_PG_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: coder-db
              key: url
        - name: CODER_OIDC_ISSUER_URL
          value: https://auth.kennyandries.com
        - name: CODER_OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: coder-oidc
              key: clientId
        - name: CODER_OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: coder-oidc
              key: clientSecret
        - name: CODER_OIDC_SIGN_IN_TEXT
          value: Sign in with Pocket ID
        - name: CODER_OIDC_SCOPES
          value: openid,profile,email
