apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - sealedsecret.yaml
  - sealedsecret-oidc.yaml
  - postgres.yaml
  - helmrelease.yaml
  - ingress.yaml
  - networkpolicy.yaml
