---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: coder-oidc
  namespace: coder
spec:
  encryptedData:
    clientId: AgAj4CU8l5PcKKk7z02qU5bU7mO0AhoSrq5DNwrs2eTwwveQuB8g9lmdnGMQaofBajsOMl2rJxrp8QRwNcAr/XEMRnVvODGPquY4qgBV88/Pf8Z1KxNlM/JMFEoXlx/xiS7Hq/LVjsg1djV5nFLsHHyoelQgC8UcujKPv53LJmR9B/Mg8ZrWEeY6nbmaO38GyhRtIhox0VEelvf3ajb73Hr0VcBOcl/AS8KlDs8AUyCqPLnbQjd5BirnbmzNYx2PM8bnXUYiiRAmsPBNZuVLMnhDnW1NMh85VoDmwRVw7n5skmVs1eYiQvR672/jWWeM04JBFcZ0tX0yp7g2/AdWcWRw+Klsip3Ogpmo6vRW4IO30LWKuXJvqqqKnHIJkaFKDpuXFCrJSU/yts+eUmTUNBXjybI1Oibr1TZj8NbaV1F3YWG+gWW0YkeKwHK/SdGNzVSSJthiEUeCwpPdxA3ELIQHGD6nbxB9vbk8/f/iUdsKbiBCjvUFJMrZCWIcN9G793OimOFtovTK4Gp9XOEgiIi2/c0nbYZV7m1kPj3oZEF7zJ9OyTkRIqXD2Qi+K7VBYg8qRAK/rWOEbgy6Ltfq7aHTGFYmJ3GMLfnAjT/lU3ShByIk+KZ8yL0HTakOrgTKjwWYjZNwJ9+6Ru+wMPQ4wvNnDy9W+m3/HcpKNPpDTKVlB0B2khWCVeASo8aOkiP+rZAYI43iRWpwjgg2XwYsa6prHshIwsIO5HMLq9jEro7W8e8cajA=
    clientSecret: AgBFjyQjzDTO6aYL7ov/Vork233FNV8WbjGC6U25GOqhJcqkAJUIB79zYZisEVNClFhEQ7hK0e621KT9wmX48OxN7q+4y30lGDYuZtEKkeE+3h8AYAchRWYSetYuqr9347eilklYv+3OQ9RWE/dZCV8GnFAjnh4LeNz0ukbZkaP9oZvlqi4zL9Ic0GDugB1UcajiuTJ/J9OQthQ0tog1GIBuK9xi+DmT9dNFWge7ERpXtXeraMq7IVsVeDlQKbAqY9O8gKJnMO8uI3TB9QEkLdR/N9NsJmP4TrHylKtPsj8BP5MYhRBBCtJyKhjnVlmA+cCNl5iIC3xIV7V4sQNVAcJ1/DDU3TYMraZ6opvvePpGJAgf9hUL4xywauFksEw3rEUOLsVhVW97t165hcL+gXHPG3InyeF8n8jSK7E/5oR0Bfutym+fFVuND1f1lL9ibuD+myWG53jBDQZF34XUZnIGmQ4kQ9xDDca+BUmx/kwz0aLJ5X2cwDm3nto6HOFQ7T8HhwfjG2LAS+7AC7aXrNPCTXMm1S9+WG39yV9/jQWK4XujNndlMqqZmRDgh0Z1JhtWaRHdkJktELwySg1lX+1yqiLda5sQC8pDEFx2bnFoE2WN17lKmXzNO90qsIfMPSoBAA/WEyxzcjSrGlj+rT+hj+BnM3m9MuMrEqXA6E7Mf+TDDkQv4+kGyjAeqyQs20kMGnuGqQkJsKyy+ATgE/RRIeObtC0KPKFYkViBCYsPwg==
  template:
    metadata:
      name: coder-oidc
      namespace: coder
    type: Opaque
